export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_CLEAR = "LOGIN_CLEAR"

export const SIGNUP_START = "SIGNUP_START"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
export const SIGNUP_CLEAR = "SIGNUP_CLEAR"

export const CREATE_TASK_START = "CREATE_TASK_START"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR"
export const CREATE_TASK_CLEAR = "CREATE_TASK_CLEAR"


export const READ_TASK_START = "READ_TASK_START"
export const READ_TASK_SUCCESS = "READ_TASK_SUCCESS"
export const READ_TASK_ERROR = "READ_TASK_ERROR"
export const READ_TASK_CLEAR = "READ_TASK_CLEAR"

export const UPDATE_TASK_START = "UPDATE_TASK_START"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR"
export const UPDATE_TASK_CLEAR = "UPDATE_TASK_CLEAR"

export const DELETE_TASK_START = "DELETE_TASK_START"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR"
export const DELETE_TASK_CLEAR = "DELETE_TASK_CLEAR"

export const MY_PROFILE_START = "MY_PROFILE_START"
export const MY_PROFILE_SUCCESS = "MY_PROFILE_SUCCESS"
export const MY_PROFILE_ERROR = "MY_PROFILE_ERROR"
export const MY_PROFILE_CLEAR = "MY_PROFILE_CLEAR"

export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"
export const DELETE_USER_CLEAR = "DELETE_USER_CLEAR"